-- liquibase formatted sql

-- changeset liquibase:4
CREATE TABLE SHOP_USER
(
    ID_USER               INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SHOP_USER_ROLE     INT REFERENCES SHOP_USER_ROLE (ID_SHOP_USER_ROLE),
    ID_SHOP_USER_STATUS   INT REFERENCES SHOP_USER_STATUS (ID_SHOP_USER_STATUS),
    USER_NAME             VARCHAR(64)              DEFAULT NULL,
    USER_LAST_NAME        VARCHAR(64)              DEFAULT NULL,
    CREATION_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
